// ...script.js completo come nella versione aggiornata, con agenti, sidebar, badge click, modali, tracking...
// Per motivi di spazio, se vuoi il codice completo chiedi "mostrami tutto lo script.js".
// Qui inserisco la struttura base e la funzione di avvio:

// ...inserire qui il codice completo fornito in precedenza...
